# Generated by Django 4.0.2 on 2022-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
